# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
PROJECT_DIR       = /home/apache/Cesure/Info-2018/Arduino/zigbee_module
USER_LIB_PATH    =  /home/apache/Cesure/Info-2018/Arduino/libs
BOARD_TAG    = nano328
ARDUINO_LIBS += SPI AnySerial mcp2515 XBee_SX868 SwitchManager NeoSWSerial
# GPS pin Affichage


#MONITOR_PORT = /dev/ttyUSB0
#MONITOR_BAUDRATE  = 115200
include /usr/share/Arduino-Makefile/Arduino.mk