# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
PROJECT_DIR       = ./

USER_LIB_PATH    =  ../libs

ARDUINO_LIBS += protocol\
				HC_SR04\
				SonarArray\
				StandardCplusplus
# SPI mcp2515

BOARD_TAG	=	nano328
#BOARD_TAG    = mega2560

#BOARD_TAG    = leonardo
#BOARD_TAG    = nano328
#BOARD_TAG   = nano
#BOARD_TAG         = promicro16
#BOARD_TAG = mega_pic32
#BOARD_TAG         = pinoccio256
#BOARD_TAG = fio
#BOARD_TAG    = atmegang
#BOARD_TAG          = attiny85at8
#BOARD_TAG      = attiny85at8
#BOARD_TAG      = attiny85
#BOARD_TAG      = attiny
#BOARD_TAG 	 = teensy31
#BOARD_TAG         = mighty_opt
#BOARD_TAG    = atmega328	
#BOARD_TAG    = mega

#MONITOR_PORT = /dev/ttyUSB0
#MONITOR_BAUDRATE  = 115200
include /usr/share/Arduino-Makefile/Arduino.mk