#include "Arduino.h"

#define SONAR_0_ECHO	10
#define SONAR_0_TRIG	11
#define SONAR_1_ECHO	8
#define SONAR_1_TRIG	9
#define SONAR_2_ECHO	6
#define SONAR_2_TRIG	7
#define SONAR_3_ECHO	A0
#define SONAR_3_TRIG	13
#define SONAR_4_ECHO	A2
#define SONAR_4_TRIG	A1
#define SONAR_5_ECHO	A3
#define SONAR_5_TRIG	12

#define SERVO_0		3
#define SERVO_1		5

#define SONAR_FRONT_L_ECHO	SONAR_0_ECHO
#define SONAR_FRONT_L_TRIG	SONAR_0_TRIG
#define SONAR_FRONT_R_ECHO	SONAR_2_ECHO
#define SONAR_FRONT_R_TRIG	SONAR_2_TRIG
#define SONAR_L_ECHO		SONAR_3_ECHO
#define SONAR_L_TRIG		SONAR_3_TRIG
#define SONAR_R_ECHO		SONAR_5_ECHO
#define SONAR_R_TRIG		SONAR_5_TRIG
#define SONAR_BACK_ECHO		SONAR_4_ECHO
#define SONAR_BACK_TRIG		SONAR_4_TRIG



#define UP 			true
#define DOWN 		false
