#include "Arduino.h"

#define SONAR_0_ECHO	40
#define SONAR_0_TRIG	41
#define SONAR_1_ECHO	28
#define SONAR_1_TRIG	29
#define SONAR_2_ECHO	30
#define SONAR_2_TRIG	31
#define SONAR_3_ECHO	48
#define SONAR_3_TRIG	49
#define SONAR_4_ECHO	46
#define SONAR_4_TRIG	47

#define SONAR_FRONT_L_ECHO	SONAR_2_ECHO
#define SONAR_FRONT_L_TRIG	SONAR_2_TRIG
#define SONAR_FRONT_R_ECHO	SONAR_3_ECHO
#define SONAR_FRONT_R_TRIG	SONAR_3_TRIG
#define SONAR_BACK_L_ECHO		SONAR_1_ECHO
#define SONAR_BACK_L_TRIG		SONAR_1_TRIG
#define SONAR_BACK_R_ECHO		SONAR_4_ECHO
#define SONAR_BACK_R_TRIG		SONAR_4_TRIG
#define SONAR_BACK_ECHO		SONAR_0_ECHO
#define SONAR_BACK_TRIG		SONAR_0_TRIG

#define MOTOR_A_IN_1	4
#define MOTOR_A_IN_2	7
#define MOTOR_A_EN		5
#define MOTOR_B_IN_1	8
#define MOTOR_B_IN_2	9
#define MOTOR_B_EN		6

#define STEPPER_STEP	36
#define STEPPER_DIR		38

#define AX12_SERIAL 	Serial3

#define PLIERS_LIMIT_SWITCH_PIN	27
#define SPI_SS_PIN	53
